# Generated by Django 5.2.12 on 2026-04-21 01:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvidenceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=60, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "categoria",
                "verbose_name_plural": "categorias",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=30, unique=True, verbose_name="código"),
                ),
                (
                    "nome",
                    models.CharField(max_length=120, verbose_name="nome da operação"),
                ),
                ("departamento", models.CharField(max_length=120)),
                (
                    "responsavel",
                    models.CharField(max_length=120, verbose_name="chefe responsável"),
                ),
                ("data_operacao", models.DateField(verbose_name="data da operação")),
                (
                    "horario_previsto",
                    models.TimeField(
                        blank=True, null=True, verbose_name="horário previsto"
                    ),
                ),
                (
                    "local_apreensao",
                    models.CharField(max_length=255, verbose_name="local da apreensão"),
                ),
                (
                    "cidade_uf",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="cidade / UF"
                    ),
                ),
                (
                    "suspeito_nome",
                    models.CharField(max_length=120, verbose_name="suspeito / alvo"),
                ),
                (
                    "suspeito_documento",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="documento do suspeito"
                    ),
                ),
                (
                    "suspeito_endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="endereço do suspeito"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejada", "Planejada"),
                            ("em_andamento", "Em andamento"),
                            ("encerrada", "Encerrada"),
                        ],
                        default="planejada",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("encerrada_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "operação",
                "verbose_name_plural": "operações",
                "ordering": ("-data_operacao", "-criado_em"),
            },
        ),
        migrations.CreateModel(
            name="SeizedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=120, verbose_name="item apreendido"),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                (
                    "local_encontrado",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="local encontrado"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="estado / condição"
                    ),
                ),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="apreensoes.evidencecategory",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="apreensoes.operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "item apreendido",
                "verbose_name_plural": "itens apreendidos",
                "ordering": ("-criado_em",),
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("cargo", models.CharField(max_length=80)),
                ("matricula", models.CharField(blank=True, max_length=30)),
                ("contato", models.CharField(blank=True, max_length=60)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="apreensoes.operation",
                    ),
                ),
            ],
            options={
                "verbose_name": "integrante da equipe",
                "verbose_name_plural": "integrantes da equipe",
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="CategoryField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80, verbose_name="rótulo")),
                ("key", models.CharField(blank=True, max_length=50)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto curto"),
                            ("textarea", "Texto longo"),
                            ("integer", "Número inteiro"),
                            ("decimal", "Número decimal"),
                            ("date", "Data"),
                            ("boolean", "Sim / Não"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="tipo do campo",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=False, verbose_name="obrigatório"),
                ),
                (
                    "help_text",
                    models.CharField(blank=True, max_length=160, verbose_name="ajuda"),
                ),
                ("placeholder", models.CharField(blank=True, max_length=120)),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="ordem"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_definitions",
                        to="apreensoes.evidencecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "campo da categoria",
                "verbose_name_plural": "campos da categoria",
                "ordering": ("sort_order", "label"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "key"), name="unique_category_key"
                    )
                ],
            },
        ),
    ]
