# Generated by Django 5.2.12 on 2026-04-26 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apreensoes", "0002_seed_default_categories"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operation",
            options={
                "ordering": ("-data_operacao", "-criado_em"),
                "verbose_name": "operacao",
                "verbose_name_plural": "operacoes",
            },
        ),
        migrations.AddField(
            model_name="seizeditem",
            name="ai_analysis",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="seizeditem",
            name="ai_analysis_model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="seizeditem",
            name="ai_analysis_provider",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="seizeditem",
            name="ai_last_analyzed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seizeditem",
            name="evidence_image",
            field=models.FileField(
                blank=True,
                upload_to="apreensoes/imagens/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "gif"]
                    )
                ],
                verbose_name="imagem do item",
            ),
        ),
        migrations.AlterField(
            model_name="categoryfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Texto curto"),
                    ("textarea", "Texto longo"),
                    ("integer", "Numero inteiro"),
                    ("decimal", "Numero decimal"),
                    ("date", "Data"),
                    ("boolean", "Sim / Nao"),
                ],
                default="text",
                max_length=20,
                verbose_name="tipo do campo",
            ),
        ),
        migrations.AlterField(
            model_name="categoryfield",
            name="label",
            field=models.CharField(max_length=80, verbose_name="rotulo"),
        ),
        migrations.AlterField(
            model_name="categoryfield",
            name="required",
            field=models.BooleanField(default=False, verbose_name="obrigatorio"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="codigo",
            field=models.CharField(max_length=30, unique=True, verbose_name="codigo"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="data_operacao",
            field=models.DateField(verbose_name="data da operacao"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="horario_previsto",
            field=models.TimeField(
                blank=True, null=True, verbose_name="horario previsto"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="local_apreensao",
            field=models.CharField(max_length=255, verbose_name="local da apreensao"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="nome",
            field=models.CharField(max_length=120, verbose_name="nome da operacao"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="responsavel",
            field=models.CharField(max_length=120, verbose_name="chefe responsavel"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="suspeito_endereco",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="endereco do suspeito"
            ),
        ),
        migrations.AlterField(
            model_name="seizeditem",
            name="estado",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="estado / condicao"
            ),
        ),
    ]
