# Generated by Django 5.2.12 on 2026-05-13 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apreensoes', '0005_seed_municoes_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='operation',
            name='houve_arrombamento_desobediencia',
            field=models.BooleanField(default=False, verbose_name='arrombamento por desobediencia'),
        ),
        migrations.AddField(
            model_name='operation',
            name='houve_emprego_forca',
            field=models.BooleanField(default=False, verbose_name='emprego de forca (recalcitrancia)'),
        ),
        migrations.AddField(
            model_name='operation',
            name='morador_ausente_arrombamento',
            field=models.BooleanField(default=False, verbose_name='morador ausente e arrombamento'),
        ),
        migrations.AddField(
            model_name='operation',
            name='obs_arrombamento_desobediencia',
            field=models.TextField(blank=True, verbose_name='observacoes (desobediencia)'),
        ),
        migrations.AddField(
            model_name='operation',
            name='obs_emprego_forca',
            field=models.TextField(blank=True, verbose_name='observacoes (recalcitrancia)'),
        ),
        migrations.AddField(
            model_name='operation',
            name='obs_morador_ausente',
            field=models.TextField(blank=True, verbose_name='observacoes (morador ausente)'),
        ),
        migrations.AddField(
            model_name='operation',
            name='observacoes_complementares',
            field=models.TextField(blank=True, verbose_name='observacoes complementares'),
        ),
        migrations.AddField(
            model_name='operation',
            name='processo_numero',
            field=models.CharField(blank=True, max_length=60, verbose_name='numero do processo'),
        ),
        migrations.AddField(
            model_name='operation',
            name='protocolo_numero',
            field=models.CharField(blank=True, max_length=60, verbose_name='numero do protocolo'),
        ),
        migrations.AddField(
            model_name='operation',
            name='vara_criminal',
            field=models.CharField(blank=True, max_length=120, verbose_name='vara criminal / juizo'),
        ),
        migrations.CreateModel(
            name='OperationWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, verbose_name='RG')),
                ('filiacao', models.CharField(blank=True, max_length=200, verbose_name='filiacao')),
                ('telefone', models.CharField(blank=True, max_length=60)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade_uf', models.CharField(blank=True, max_length=120, verbose_name='cidade / UF')),
                ('tipo', models.CharField(choices=[('geral', 'Testemunha Geral'), ('vizinho', 'Testemunha/Vizinho (Morador Ausente)')], default='geral', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to='apreensoes.operation')),
            ],
            options={
                'verbose_name': 'testemunha',
                'verbose_name_plural': 'testemunhas',
                'ordering': ('nome',),
            },
        ),
    ]
